import { Metadata } from 'next';
import { Providers } from '../providers'
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   manifest: "/manifest.json", // <-- add here the route of manifest.json
// };

type Props = {
  children: React.ReactNode,
  params: { locale: string }
}

export default async function RootLayout({children, params:{locale}}: Props) {
  const message = await getMessages()
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={message}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}